database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "vibe_auth"
  sslmode: "disable"

grpc:
  port: 50032
  timeout: 60s
redis:
  host: "localhost"
  port: "6379"
  password: "password"

JWT:
  secret: "008b057678d1f6cbc8ddced4b387b92334006894686164d1de8efe957c74ed88"
