version: "3.9"

services:
  auth-service:
    build:
      context: ../services/auth-service
    ports:
      - "50051:50051"
    env_file:
      - ../services/auth-service/.env
    depends_on:
      - postgres-auth
    volumes:
      - ../migrations/auth-service:/app/migrations

  envoy:
    image: envoyproxy/envoy:tools-v1.34.1
    container_name: envoy
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - "./envoy.yaml:/etc/envoy/envoy.yaml:ro"
    restart: unless-stopped
  postgres-auth:
    image: postgres:16
    container_name: vibe-auth-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vibe_auth
    ports:
      - "5432:5432"
    volumes:
      - pgdata-auth:/var/lib/postgresql/data
      - ./postgres/custom-pg_hba.conf:/etc/postgresql/custom-pg_hba.conf
      - ./postgres/custom-postgresql.conf:/etc/postgresql/custom-postgresql.conf
    command: [
      "postgres",
      "-c", "config_file=/etc/postgresql/custom-postgresql.conf"
    ]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=password
    volumes:
      - redis_data:/data
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]

volumes:
  pgdata-auth:
  redis_data:
#  mongo-data: