version: "3.9"

services:
  postgres-auth:
    image: postgres:16
    container_name: vibe-auth-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vibe_auth
    ports:
      - "5432:5432"
    volumes:
      - pgdata-auth:/var/lib/postgresql/data
      - ./postgres/custom-pg_hba.conf:/etc/postgresql/custom-pg_hba.conf
      - ./postgres/custom-postgresql.conf:/etc/postgresql/custom-postgresql.conf
    command: [
      "postgres",
      "-c", "config_file=/etc/postgresql/custom-postgresql.conf"
    ]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  # redis:
  #   image: redis:7
  #   container_name: vibe-redis
  #   restart: unless-stopped
  #   ports:
  #     - "6379:6379"
  # mongo:
  #   image: mongo:6
  #   container_name: vibe-mongo
  #   restart: unless-stopped
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo-data:/data/db
volumes:
  pgdata-auth:
#  mongo-data: