apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-service-sa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      serviceAccountName: auth-service-sa
      containers:
        - name: auth
          image: auth-service:latest
          ports:
            - containerPort: 50051
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051